---
os: linux
dist: focal
language: python
python:
  - 3.10
  - 3.9
  - 3.8
  - 3.7
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
env:
  global:
stages:
  - name: test
  - name: publish
    if: tag IS present
install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pylint xslproxy
  - pyflakes src/xslproxy
  - trial src/xslproxy/test/*.py
jobs:
  include:
    - stage: publish
      install: skip
      script: skip
      deploy:
        on:
          all_branches: true
        provider: pypi
        distributions: sdist bdist_wheel
        username: "__token__"
        password:
          secure: "LNczVpC5pJ47j9y125qBQpmuQlZGFrSuxOh9TeK2fxE8i2NC5LlgUWy8xBt/SvwWD/5sp3ZsnnBEV9Gb90/QO2toIS4xTJd/YfAQqA6c1W1hps2Ti8faDG3atnbdpV+h5+2ESLS0JBKuoqm5cy1CPKyE4316j26F61+ws2HwNp3EeiesD6kHKp+euVR9d9UqHq3ovJA8HE6RwXtFm/bYsoVlCs68SJ4PDvABJNkRcqppN+zLgeuW9PQEH5HTV578DJyMHBThauNztvTVZB/OiObZ57fJLA3J9PsogUD7jUqWsOhDrlxx7JMSwPWeXL33lSWrRG7+FoNsx+ed05vm3mGSy6of/H9vah1Tcugda8XYzYfxrOZV3TZwylo011+z0HOrXea02KxP8EqUNGJr9IT2NSKPeiFkVgQvOF/T5QzUwTN8BpyudFQL8ceYyjs8oU6jFtOKR9nukXeowoRALTk9Zm+WsWuvA6NBgE9zF9JVwW1p/72Zmt8O7udvKcv/x/f/mwV2Dlma+ybGjKnDronboDWEQcJvIg2gghIQyZjsg9aL5aZlNEoqwfw0b29sBYLsgRf1UIfElRg1H3BvDEMNcj6Yy6a3n/eIOH1wRcrsfGbUVqKOKACMloR04NLmr3P/3+aGSs1T8ekrej7s3criioQ6NM7zNrUH/DIltis="
